### ISSUE TITLE
module.exports Uses ES2015 Arrow Function

### ISSUE THREAD

**Issue by Alamantus** [sindresorhus/copy-text-to-clipboard#19]
Using an ES6 arrow function prevents older browsers (specifically any version of IE) from running the script at all. This is a problem because this package is used as a dependency for several other packages—in my case `state-copy`, which is a dependency of `choo-devtools`. Because Babel does not run on dependencies, the arrow function copies through in transpiled code, which prevents it from running on IE.

The fix is simply replacing the arrow function with a regular JS function.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/copy-text-to-clipboard/pull/20#issuecomment-391467726
