### ISSUE TITLE
Provide TypeScript declaration

### ISSUE THREAD

**Issue by til-schneider** [sindresorhus/copy-text-to-clipboard#25]
You should provide a TypeScript declaration, so `copy-text-to-clipboard` can seamlessly be used in TypeScript. This would also provide auto-completion for JavaScript users in some editors.

Just add a file called `index.d.ts` with the following content:

```ts
/**
 * Copy `text` to the clipboard.
 * Must be called in response to a user gesture event, like `click` or `keyup`.
 *
 * @return whether copying succeeded
 */
export default function copy(text: string): boolean
```

**Comment by sindresorhus** [comment]
Fixed by #24
