### ISSUE TITLE
TypeScript error: Cannot compile namespaces when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by fritx** [sindresorhus/copy-text-to-clipboard#27]
![image](https://user-images.githubusercontent.com/6647633/55958824-1a746500-5c9c-11e9-8cb2-da5dab8a8a62.png)

When I import this library in ts it shows such error:

```js
import copy from 'copy-text-to-clipboard';
```

Donno if is related to these:
- https://github.com/lingui/js-lingui/issues/377
- https://stackoverflow.com/questions/33977054/cannot-compile-namespaces-when-the-isolatedmodules-flag-is-provided

**Comment by sindresorhus** [comment]
Depending on your tsconfig, you might have to import it like `import copy = require('copy-text-to-clipboard');`. Regardless, this is not a problem with this module.
