### ISSUE TITLE
Change the script url in the demo on jsfiddle?

### ISSUE THREAD

**Issue by maple3142** [sindresorhus/copy-text-to-clipboard#31]
The [demo](https://jsfiddle.net/sindresorhus/6406v3pf/) won't work at all since https://wzrd.in/standalone/copy-text-to-clipboard is broken.
Maybe switch to some similar services like [bundle.run](https://bundle.run/copy-text-to-clipboard@2.1.0) to make it work again.

**Comment by sindresorhus** [comment]
Fixed now

**Comment by Epithumia** [comment]
The current version on bundle.run is also broken ("package has no entry file; please specify a `module` key in your `package.json`.").
