### ISSUE TITLE
l.append is not a function

### ISSUE THREAD

**Issue by ghashi** [sindresorhus/copy-text-to-clipboard#36]
I'm seeing this error "l.append is not a function" when executing the following line:

```
const didCopy = copy(copyText)
```

It seems the error comes from this line:
```
target.append(element);
```

# more info

item | description
-- | --
User-Agent | Mozilla/5.0 (Linux; Android 7.1.1; MotoG3 Build/NMF26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/259.0.0.18.120;]/FB_MEXT_IAB
Device Brand | Motorola
Device Family | MotoG3
Device Model | G3
Browser name | Facebook (webview of Messenger)
Browser version | 259.0.0
OS Name | Android
OS Version | 7.1.1

--

Any suggestions? I think it is related to the browser, right?

**Comment by sindresorhus** [comment]
This browser is based on Chrome 52, while `.append` is only available in Chrome 54 and later: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append
