### ISSUE TITLE
Doesn't work without requirejs.

### ISSUE THREAD

**Issue by fabiocaccamo** [sindresorhus/copy-text-to-clipboard#37]
Hello I'm try to use this library directly from cdn: 
```html
<script src="https://cdn.jsdelivr.net/npm/copy-text-to-clipboard@2.2.0/index.js" integrity="sha256-yDOY9y0ETQ5jNdYMNQnGn59QEdayQyLv8WYQ57TTeo4=" crossorigin="anonymous"></script>
```
but it throws the following exception: `Uncaught ReferenceError: module is not defined`.

requirejs seems to be mandatory, that's an unnecessary limit.

**Comment by sindresorhus** [comment]
I don't know how JSDeliver works, but you need a build tool to use this package, like Webpack.
