### ISSUE TITLE
Question about style.contain and style.all

### ISSUE THREAD

**Issue by ruanyl** [sindresorhus/copy-text-to-clipboard#4]
Hi, it seems `style.contain` is an experimental technology, not all major browsers support `style.all`, will it cause cross-browser issue? Have you tested it?

```
el.style.contain = 'strict';
el.style.all = 'unset';
```

**Comment by fregante** [comment]
I don't think `all` is necessary (textarea's content is always only plaintext) and `contain` is just a speed enhancement, not required for the module to work.

**Comment by sindresorhus** [comment]
It's only there as an extra safeguard.

@bfred-it Someone might still do something weird to all `textarea` elements that we're not thinking of. Doesn't hurt to be extra safe.
