### ISSUE TITLE
why does node version require >= 12

### ISSUE THREAD

**Issue by hnsylitao** [sindresorhus/copy-text-to-clipboard#43]
https://github.com/sindresorhus/copy-text-to-clipboard/blob/main/package.json#L16

**Comment by sindresorhus** [comment]
Because it's a native ESM package, which requires Node.js 12 or later.

**Comment by hnsylitao** [comment]
can it support commonjs package format?

and webpack compilation also supports umd format, no node >= v12 requirement is required
