### ISSUE TITLE
Compatibility with UglifyJS

### ISSUE THREAD

**Issue by skyrpex** [sindresorhus/copy-text-to-clipboard#5]
Hi there! This package can't be minified with UglifyJS because it doesn't understand arrow functions.

I wonder if you're open to change the source to be ES5 compatible (no arrow function, maybe not even const).

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
