### ISSUE TITLE
What defines "modern browser"

### ISSUE THREAD

**Issue by scottcorgan** [sindresorhus/copy-text-to-clipboard#6]
> Copy text to the clipboard in modern browsers (0.2 kB)

Just curious what defines modern browser.

(Closing issue because it's not an issue)

**Comment by sindresorhus** [comment]
Latest version of Chrome, Firefox, Safari, Edge. If you run it through Babel it should work in any browser though.

**Comment by holloway** [comment]
I'm pretty sure Babel won't translate the DOM API usage noted in #28
